#%RAML 1.0
title: Greeting API
baseUri: http://localhost:8081/
version: 0.0.1

/greeting:
  displayName: Greeting
  get:
    description: Greet the caller
    queryParameters:
      name:
        type: string
        description: The name of the caller
    responses:
      200:
        body:
          application/json:

/guestbook/entry:
  post:
    responses:
      201:
        body:
          application/json: