openapi: "3.0.0"
info:
  title: Greeting API
  version: 0.0.1
paths:
  /greeting:
    get:
      summary: Greet the caller
      parameters:
        name: name
        in: query
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:

  /guestbook/entry:
    post:
      summary: Sign the guestbook
      responses:
        '201':
          description: |-
            201 Created
          content:
            application/json: